services:
  prompt-hub:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - prompt-hub-data:/app/prisma

volumes:
  prompt-hub-data:
